export const v3ScriptContent = `@echo off
setlocal EnableDelayedExpansion
:: BITS Portable Tool - Main Launcher
:: Version: 3.3.16 (Hotfix: Missing Label)
:: Author: Berkshire IT Services

:: ==============================================================================
:: 0. DEBUG CONFIGURATION
:: ==============================================================================
set "DEBUG_LVL=0"
set "DEBUG_LABEL="
set "CRASH_LOG=%~dp0GeminiCLI_Debug_log.txt"

if exist "%~dp0debug_level.txt" (
    for /f "usebackq tokens=1,2 delims==" %%A in ("%~dp0debug_level.txt") do (
        if /i "%%A"=="debug_level" set "DEBUG_LVL=%%B"
    )
)

:: Trim whitespace
set "DEBUG_LVL=%DEBUG_LVL: =%"

if "%DEBUG_LVL%"=="1" set "DEBUG_LABEL=CRITICAL ONLY"
if "%DEBUG_LVL%"=="2" set "DEBUG_LABEL=CRITICAL & INFO"
if "%DEBUG_LVL%"=="3" set "DEBUG_LABEL=KITCHEN SINK (VERBOSE)"

:: Initialize Log if Debugging Enabled
if %DEBUG_LVL% gtr 0 (
    (echo [STARTUP] %DATE% %TIME% - Debug Session Started [Level %DEBUG_LVL%]) > "%CRASH_LOG%" 2>nul
    if errorlevel 1 (
         set "NOW=%TIME: =0%"
         set "TS=!NOW:~0,2!!NOW:~3,2!!NOW:~6,2!"
         set "CRASH_LOG=%~dp0GeminiCLI_Debug_!TS!_log.txt"
         (echo [STARTUP] Fallback Log Created) > "!CRASH_LOG!" 2>nul
    )
) else (
    set "CRASH_LOG=nul"
)

call :dlog 3 "Debug Level: %DEBUG_LVL% (%DEBUG_LABEL%)"
call :dlog 3 "Initial Env: CD=%CD%."

:: ==============================================================================
:: 1. UNIVERSAL EXECUTION & INIT
:: ==============================================================================
call :dlog 2 "Setting working directory to: %~dp0."
pushd "%~dp0" 2>&1
if %errorlevel% neq 0 (
    call :dlog 1 "FATAL: Failed to set working directory via pushd."
    echo [FATAL] Script must be run from a valid directory.
    pause
    exit /b 1
)

:: Initialize Variables
set "VERSION=3.3.16"
set "LOGS_DIR=logs"
if not exist "%LOGS_DIR%" mkdir "%LOGS_DIR%" >nul 2>&1

:: [ENV-1] Inject Portable Node into PATH
call :dlog 2 "Updating PATH environment variable..."
set "PATH=%~dp0node;%PATH%"
call :dlog 3 "NEW PATH: %PATH%"

:: [ENV-2] Set NODE_PATH
:: Essential for CJS scripts to find modules in both locations
call :dlog 2 "Setting NODE_PATH..."
set "NODE_PATH=%~dp0node\\node_modules;%~dp0node_modules"
call :dlog 3 "NODE_PATH: %NODE_PATH%"

:: [ENV-3] Auto-Configure Node.js Environment
set "PKG_FOUND=0"
if exist "package.json" set "PKG_FOUND=1"
if exist "node\\package.json" set "PKG_FOUND=1"

call :dlog 3 "Package check: PKG_FOUND=%PKG_FOUND%"

if "%PKG_FOUND%"=="0" (
    call :dlog 2 "Creating missing package.json..."
    (
        echo {
        echo   "description": "Auto-generated by BITS Portable Tool",
        echo   "dependencies": {
        echo     "@google/genai": "^0.0.1"
        echo   }
        echo }
    ) > "package.json"
)

:: [LOG-1] Generate Log Filename
for /f "tokens=2 delims==" %%I in ('wmic os get localdatetime /value') do set datetime=%%I
set "LOGFILE=%LOGS_DIR%\\session_%datetime:~0,8%_%datetime:~8,6%.txt"
call :dlog 2 "Session Log defined: %LOGFILE%"

:: [ARCH-1] Detect Admin
call :dlog 2 "Checking Privilege Level..."
set "IS_ADMIN=0"
net session >nul 2>&1
if %errorLevel% equ 0 (
    set "IS_ADMIN=1"
    set "MODE_LABEL=ELEVATED ADMIN"
) else (
    set "MODE_LABEL=STANDARD USER"
)
call :dlog 2 "Mode: %MODE_LABEL%"

:: [INIT-1] Connectivity Check
call :dlog 2 "Checking Connectivity (Ping 8.8.8.8)..."
set "IS_ONLINE=0"
set "ONLINE_LABEL=INACTIVE"
ping -n 1 8.8.8.8 >nul 2>&1
if %errorLevel% equ 0 (
    set "IS_ONLINE=1"
    set "ONLINE_LABEL=ACTIVE"
)
call :dlog 2 "Online Status: %IS_ONLINE% (%ONLINE_LABEL%)"

:: [AI-CONFIG] Load API Key & Set Status
set "API_KEY="
set "AI_STATUS=UNKNOWN"

if "%IS_ONLINE%"=="0" (
    set "AI_STATUS=OFFLINE"
    call :dlog 2 "AI Status set to OFFLINE due to no connectivity."
    goto :ai_status_done
)

call :dlog 3 "Checking for config.txt..."
if exist "config.txt" (
    for /f "usebackq delims=" %%A in ("config.txt") do set "API_KEY=%%A"
)

if defined API_KEY (
    set "AI_STATUS=READY"
    call :dlog 2 "API Key loaded. Status: READY"
) else (
    set "AI_STATUS=NO KEY"
    call :dlog 1 "WARN: config.txt missing or empty. Status: NO KEY"
)

:: [AI-SCRIPTS-CHECK]
call :check_ai_reqs

:ai_status_done
call :dlog 3 "Init Complete. Transitioning to Telemetry."

:: ==============================================================================
:: 2. TELEMETRY
:: ==============================================================================
call :log "Session Started. Mode: %MODE_LABEL%. Version: %VERSION%"

echo [INIT] Gathering System Telemetry...
call :dlog 3 "Executing Get-CimInstance (Fast Telemetry)..."
powershell -Command "try { $os = Get-CimInstance Win32_OperatingSystem -ErrorAction Stop; $cs = Get-CimInstance Win32_ComputerSystem -ErrorAction Stop; $bios = Get-CimInstance Win32_BIOS -ErrorAction Stop; [PSCustomObject]@{OsName=$os.Caption; OsVersion=$os.Version; CsModel=$cs.Model; CsManufacturer=$cs.Manufacturer; BiosSerialNumber=$bios.SerialNumber} | Format-List } catch { Write-Host 'Telemetry Error: ' $_.Exception.Message }" >> "%LOGFILE%" 2>> "%CRASH_LOG%"

:: ==============================================================================
:: 3. MAIN DASHBOARD
:: ==============================================================================
:dashboard
@echo off
call :dlog 3 "Rendering Dashboard..."
cls 2>> "%CRASH_LOG%"

echo  ==============================================================================
echo   BITS Portable Tool v%VERSION%
echo   Mode: [%MODE_LABEL%]   ^|   Online: [%ONLINE_LABEL%]   ^|   AI: [%AI_STATUS%]
if %DEBUG_LVL% gtr 0 echo   DEBUG MODE: %DEBUG_LVL% (%DEBUG_LABEL%)
echo  ==============================================================================
echo.
echo  [1] Network Diagnostics
echo  [2] Printer Fix (Spooler)
echo  [3] Updates (Windows ^& Apps)
echo  [4] Event Log Analysis
echo  [5] Disk Cleanup
if "%IS_ADMIN%"=="0" echo  [E] Switch to Elevated Mode (Admin)
echo  [Q] Quit
echo.

call :log "Waiting for user input on Dashboard..."
choice /c 12345EQ /m "Select Action:"

if errorlevel 7 goto :eof
if errorlevel 6 goto :elevate_request
if errorlevel 5 goto :disk_clean
if errorlevel 4 goto :event_logs
if errorlevel 3 goto :update_menu
if errorlevel 2 goto :printer_fix
if errorlevel 1 goto :network_diag

:: ==============================================================================
:: SUBROUTINE: CHECK AI REQS
:: ==============================================================================
:check_ai_reqs
call :dlog 3 "Entering :check_ai_reqs"
if not "%AI_STATUS%"=="READY" exit /b

:: 1. Check Scripts (Targeting .cjs for CommonJS support)
if not exist "scripts\\gemini_net.cjs" (
    set "AI_STATUS=NO_SCRIPTS"
    call :dlog 1 "WARN: 'scripts\\gemini_net.cjs' not found."
    exit /b
)

:: 2. Check Dependencies
set "LIBS_OK=0"
if exist "node_modules\\@google\\genai\\package.json" set "LIBS_OK=1"
if exist "node\\node_modules\\@google\\genai\\package.json" set "LIBS_OK=1"

call :dlog 3 "Dependency Check Result LIBS_OK=%LIBS_OK%"

if "%LIBS_OK%"=="1" (
    call :dlog 2 "Dependencies found."
    exit /b
)

:: 3. Handle Failure
set "AI_STATUS=MISSING_LIBS"
call :dlog 1 "CRITICAL: @google/genai SDK missing."
call :dlog 3 "Searched in node_modules and node\\node_modules."
exit /b

:: ==============================================================================
:: LOGGING SUBROUTINES
:: ==============================================================================
:dlog
:: Usage: call :dlog <level> "Message"
:: Levels: 1=Critical, 2=Info, 3=Verbose
if %DEBUG_LVL% lss %1 exit /b
set "MSG=%~2"
echo [%TIME%] [DEBUG-%1] !MSG! >> "%CRASH_LOG%"
if "%DEBUG_LVL%"=="3" echo [DEBUG-%1] !MSG!
exit /b

:log
:: Public Session Logging
:: Updated v3.3.6: Uses DelayedExpansion (!LMSG!) to safely handle symbols like '&'
set "LMSG=%~1"
echo [LOG] !LMSG!
echo [%time%] !LMSG! >> "%LOGFILE%"
call :dlog 2 "USER_ACTION: !LMSG!"
exit /b

:: ==============================================================================
:: FEATURE: ELEVATION REQUEST
:: ==============================================================================
:elevate_request
call :dlog 2 "Requesting Elevation..."
if "%IS_ADMIN%"=="1" (
    call :dlog 2 "Already elevated. Ignoring."
    timeout /t 2 >nul
    goto :dashboard
)
powershell -Command "Start-Process cmd -ArgumentList '/c', 'pushd', '""%~dp0""', '&', 'call', '""%~f0""' -Verb RunAs"
exit /b

:: ==============================================================================
:: MODULE: NETWORK
:: ==============================================================================
:network_diag
cls
echo [NETWORK DIAGNOSTICS]
echo.
echo [EXTERNAL CONNECTIVITY]
powershell -Command "$wan='NONE DETECTED'; $urls=@('https://api.ipify.org','https://ident.me','https://icanhazip.com'); $protos=@(3072,768,192); Write-Host '[DEBUG] Starting WAN Probe...' -ForegroundColor DarkGray; foreach($p in $protos){ Write-Host \"  [DEBUG] Setting Protocol: $p\" -ForegroundColor DarkGray; try{[Net.ServicePointManager]::SecurityProtocol=$p}catch{Write-Host \"    [ERR] Protocol Set Failed\" -ForegroundColor Red; continue}; foreach($u in $urls){ Write-Host \"    [DEBUG] Requesting $u ... \" -NoNewline -ForegroundColor Gray; try{ $r=Invoke-RestMethod -Uri $u -Headers @{'User-Agent'='Mozilla/5.0'} -ErrorAction Stop; $clean=$r.Trim(); if($clean -as [ipaddress]){ $wan=$clean; Write-Host 'OK' -ForegroundColor Green; break } else { Write-Host \"INVALID DATA: $r\" -ForegroundColor Yellow } } catch{ Write-Host \"FAILED ($($_.Exception.Message))\" -ForegroundColor Red } }; if($wan -ne 'NONE DETECTED'){break} }; Write-Host ''; Write-Host 'WAN IP Address: ' -NoNewline; Write-Host $wan -ForegroundColor Cyan"
echo.
echo [DETECTED INTERFACES]
powershell -Command "Get-NetAdapter | Sort-Object Status | ForEach-Object { $ipObj = Get-NetIPAddress -InterfaceIndex $_.InterfaceIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue; $ip = if ($ipObj) { $ipObj.IPAddress } else { 'None Detected' }; $dnsObj = Get-DnsClientServerAddress -InterfaceIndex $_.InterfaceIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue; $dns = if ($dnsObj.ServerAddresses) { $dnsObj.ServerAddresses -join ', ' } else { 'None Detected' }; $isVPN = ($_.InterfaceDescription -match 'VPN|TAP|TUN|WireGuard|GlobalProtect|Cisco|Fortinet') -or ($_.Name -match 'VPN'); $tag = if ($isVPN) { '<- VPN DETECTED' } else { '' }; [PSCustomObject]@{Name=$_.Name; Status=$_.Status; 'IP Addr'=$ip; 'DNS Servers'=$dns; 'VPN Check'=$tag} } | Format-Table -AutoSize"
echo.
echo ----------------------------------------
echo [1] Wi-Fi Diagnostics (Checks WLAN)
echo [2] Standard Diagnostics (All Interfaces)
echo [3] Back
echo ----------------------------------------
choice /c 123 /m "Select Interface Mode:"

if errorlevel 3 goto :dashboard
if errorlevel 2 goto :net_run_general
if errorlevel 1 goto :net_run_wifi

:net_run_wifi
call :log "Checking for Wireless Interface..."
set "WIFI_TEMP=%TEMP%\\wifi_audit.tmp"
netsh wlan show interfaces > "%WIFI_TEMP%" 2>&1

:: Simple checks
findstr /i "Name" "%WIFI_TEMP%" >nul
if %errorlevel% neq 0 (
    call :dlog 2 "Wi-Fi check failed. No Name found in output."
    goto :wifi_missing
)

call :log "Wi-Fi Adapter detected. Gathering capabilities & scans..."
echo -------------------------------- >> "%LOGFILE%"
echo [WLAN INTERFACES] >> "%LOGFILE%"
type "%WIFI_TEMP%" >> "%LOGFILE%"
if exist "%WIFI_TEMP%" del "%WIFI_TEMP%"

echo [WLAN DRIVERS] >> "%LOGFILE%"
netsh wlan show drivers >> "%LOGFILE%"

echo [WLAN CAPABILITIES] >> "%LOGFILE%"
netsh wlan show capabilities >> "%LOGFILE%"

echo [WLAN AUTOCONFIG] >> "%LOGFILE%"
netsh wlan show settings >> "%LOGFILE%"

echo [VISIBLE NETWORKS (BSSID)] >> "%LOGFILE%"
netsh wlan show networks mode=bssid >> "%LOGFILE%"

if "%IS_ADMIN%"=="1" (
    echo [WLAN REPORT - ADMIN] >> "%LOGFILE%"
    netsh wlan show wlanreport >> "%LOGFILE%"
)
goto :net_run_general

:wifi_missing
call :log "No Wi-Fi adapter detected."
echo [WARN] WLAN Interface not found or disabled.
echo        Skipping deep WLAN analysis...
timeout /t 2 >nul
goto :net_run_general

:net_run_general
call :log "Running Comprehensive Network Diagnostics..."

echo -------------------------------- >> "%LOGFILE%"
echo [IPCONFIG] >> "%LOGFILE%"
ipconfig /all >> "%LOGFILE%"

echo [DNS RESOLUTION TEST] >> "%LOGFILE%"
nslookup google.com >> "%LOGFILE%" 2>&1

echo [INTERFACE ADMIN STATE] >> "%LOGFILE%"
netsh interface show interface >> "%LOGFILE%"

echo [ARP CACHE] >> "%LOGFILE%"
arp -a >> "%LOGFILE%"

echo [ROUTING TABLE] >> "%LOGFILE%"
route print -4 >> "%LOGFILE%"

echo [PING TEST] >> "%LOGFILE%"
ping -n 4 8.8.8.8 >> "%LOGFILE%"

if "%AI_STATUS%"=="READY" goto :net_ai_run
if "%AI_STATUS%"=="MISSING_LIBS" goto :net_ai_libs_err
goto :net_done

:net_ai_libs_err
echo [ERROR] AI Libraries not found.
goto :net_done

:net_ai_run
call :log "Triggering Gemini Analysis..."
echo [GEMINI] Analyzing Network Logs...

if not exist "scripts\\gemini_net.cjs" goto :net_done

where node >nul 2>nul
if %errorlevel% equ 0 (
     call :dlog 3 "EXEC NODE: node scripts\\gemini_net.cjs %~dp0%LOGFILE%"
     node "scripts\\gemini_net.cjs" "%~dp0%LOGFILE%"
)

:net_done
pause
goto :dashboard

:: ==============================================================================
:: MODULE: PRINTER FIX
:: ==============================================================================
:printer_fix
cls
echo [PRINTER DIAGNOSTICS]
sc query spooler >> "%LOGFILE%"
echo [1] Restart Spooler (Admin Only)
echo [2] View Print Jobs
echo [3] Back
choice /c 123 /m "Select:"

if errorlevel 3 goto :dashboard
if errorlevel 2 (
    powershell "Get-PrintJob -PrinterName *"
    pause
    goto :printer_fix
)
if errorlevel 1 (
    if "%IS_ADMIN%"=="0" (
        echo [ACCESS DENIED] Requires Admin.
        pause
        goto :printer_fix
    )
    net stop spooler
    del /F /Q %systemroot%\System32\spool\PRINTERS\*
    net start spooler
    echo Spooler restarted.
    pause
    goto :printer_fix
)

:: ==============================================================================
:: MODULE: UPDATES
:: ==============================================================================
:update_menu
cls
echo [UPDATES]
echo 1. Windows Update Scan
echo 2. Windows Update Repair (Admin)
echo 3. App Updates (Winget)
echo 4. Native Troubleshooter
echo 5. Back
choice /c 12345 /m "Select:"

if errorlevel 5 goto :dashboard
if errorlevel 4 (
    msdt.exe /id WindowsUpdateDiagnostic
    goto :update_menu
)
if errorlevel 3 (
    winget upgrade
    pause
    goto :update_menu
)
if errorlevel 2 (
    if "%IS_ADMIN%"=="0" (
        echo [ACCESS DENIED] Requires Admin.
        pause
        goto :update_menu
    )
    net stop wuauserv
    net stop cryptSvc
    ren %WINDIR%\\SoftwareDistribution SoftwareDistribution.bak
    net start wuauserv
    net start cryptSvc
    pause
    goto :update_menu
)
if errorlevel 1 (
    usoclient StartScan
    pause
    goto :update_menu
)

:: ==============================================================================
:: MODULE: EVENT LOGS
:: ==============================================================================
:event_logs
cls
echo [EVENT LOGS - LAST 14 DAYS]
echo Exporting logs...
powershell -Command "Get-WinEvent -FilterHashtable @{LogName='System'; Level=1,2,3; StartTime=(Get-Date).AddDays(-14)} -ErrorAction SilentlyContinue | Select-Object TimeCreated, Id, Message | Format-Table -AutoSize" > "%LOGS_DIR%\\events.txt"
type "%LOGS_DIR%\\events.txt"

if "%AI_STATUS%"=="READY" goto :event_ai_run
goto :event_done

:event_ai_run
echo [GEMINI] Analyzing Event Patterns...
where node >nul 2>nul
if %errorlevel% equ 0 (
    call :dlog 3 "EXEC NODE: node scripts\\gemini_events.cjs %~dp0%LOGS_DIR%\\events.txt"
    node "scripts\\gemini_events.cjs" "%~dp0%LOGS_DIR%\\events.txt"
)

:event_done
pause
goto :dashboard

:: ==============================================================================
:: MODULE: DISK CLEAN
:: ==============================================================================
:disk_clean
cls
echo [DISK CLEANUP]
del /q /f /s "%TEMP%\\*" >nul 2>&1

if "%IS_ADMIN%"=="1" (
    echo [SAFETY] Creating System Restore Point...
    powershell -Command "Checkpoint-Computer -Description 'GeminiCLI_Cleanup' -RestorePointType 'MODIFY_SETTINGS' -ErrorAction SilentlyContinue"
    del /q /f /s "%WINDIR%\\Temp\\*" >nul 2>&1
)
pause
goto :dashboard
`;